version: "3.7"
services:
  # flask_app:
  #   build: './flask_app'
  #   environment:
  #     - REDIS_URL=redis
  #     - REDIS_PORT=6379
  #   ports:
  #     - "5006:5000"
  #   depends_on:
  #     - redis

  fastapi_app:
    build: '.'
    environment:
      # - REDIS_URL=redis
      - REDIS_URL=redis://redis:6379/0
      - REDIS_PORT=6379
    ports:
      - "5005:5000"
    depends_on:
      - redis
    networks:
      - lapisco-network

  # db:
  #   image: postgres:12.1
  #   ports:
  #     - '$DB_PORT:$DB_PORT'
  #   environment:
  #     - POSTGRES_USER=$DB_USER
  #     - POSTGRES_PASSWORD=$DB_PASS
  #     - POSTGRES_DB=$DB_NAME
  #   env_file: .env      
  #   volumes:
  #      - lapisco-network:/data/postgres
  #   networks:
  #     - lapisco-network

  # pgadmin:
  #   container_name: lapisco-pgadmin
  #   image: dpage/pgadmin4:4.16
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #   volumes:
  #      - lapisco-pgadmin:/root/.pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-5050}:80"
  #   networks:
  #     - lapisco-network
  #   depends_on: 
  #     - db

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    networks:
      - lapisco-network
      

  simple_worker:
    build: './simple_worker'
    user: nobody
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - lapisco-network



networks:
  lapisco-network:
    driver: bridge

volumes:
  lapisco-network:
  # lapisco-pgadmin:    